name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install

      - name: Build project
        run: npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # 必须与vite.config.js的outDir一致

      - name: Verify Artifact Upload
        run: |
          echo "Listing all artifacts in repository..."
          ARTIFACTS=$(gh api repos/{owner}/{repo}/actions/artifacts | jq -r '.artifacts[].name')
          echo "Found artifacts: $ARTIFACTS"
          if [[ ! $ARTIFACTS =~ "github-pages" ]]; then
            echo "Error: github-pages artifact not found!"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.CICD_DEMO_TOKEN }}
          artifact_name: github-pages
          check_run_id: ${{ needs.build-and-test.result }}
          publish_dir: ./dist